### ISSUE TITLE
App crashes when saving film on screen rotation

### ISSUE THREAD

**Issue by Olamatto** [zouroboros/filmchecker#12]
#### Expected behavior
Application is expected to work perfectly well on any screen orientation, and save film without crashing. 

#### Actual Behavior 
When trying to create a DM on screen rotation the app crashes 

#### How to reproduce
- Download and install the application [here](
https://play.google.com/store/apps/details?id=xyz.iridiumion.enlightened)
- Switch on your data connection 
- Launch the application 
- Click on the add button (+)
- Select DM
- Input in some figures 
- Click on Save film (Film speichern)
- While it is loading, rotate your screen

Then app crashes 

<hr>

Application version: v1.4.1.0
Operating system: Android v7.0

#### Recording Of The Bug
https://youtu.be/Xq43CKKa-uM

**Comment by zouroboros** [comment]
Thanks for reporting the bug, I will look into that.

**Comment by zouroboros** [comment]
This should fix the issue. Can you report back is this indeed fixed your problem?

**Comment by zouroboros** [comment]
The new version 1.4.2 with the bug fix should be in f-droid in a week or so
