### ISSUE TITLE
New logo proposal for FilmChecker app

### ISSUE THREAD

**Issue by ammarraisafti** [zouroboros/filmchecker#17]
Hi admin, I want to offer a simple new logo design for FilmChecker application. This logo is my special design for you.If you are willing to accept it, you simply reply to this proposal.I will send you a new logo of this file.And if you want other color variations , you can tell me. Thanks

![filmchecker](https://user-images.githubusercontent.com/37721970/41534956-a9a65afa-732a-11e8-9aee-ee3233fa4b5b.png)

**Comment by zouroboros** [comment]
Thanks for your effort. But I prefer the current logo. Also note that the FilmChecker app is for checking the status of photographic film orders not movie orders, so the logos you proposed wouldn't fit anyway.
