### ISSUE TITLE
FilmChecker v 2.0.2 - An error occurred while adding a movie 

### ISSUE THREAD

**Issue by ammarraisafti** [zouroboros/filmchecker#24]
# Actual behaviour
After ensuring a good internet connection.  Then I added the Rossmann (Germany) movie, then filled the zip code store.  Supposedly, that ability can be done.

# Expected behaviour
When adding the Rossmann (German) film, after filling in the postcode store. An error occurred, which led to the internet network.  

Even though I have a good and stable internet connection.  I can't add Rossmann (Germany) movies.

# Step to reproduce
- Install and open the application
- Click the add icon, then select Rossmann (Germany).
- Enter store zip code
- Then you will find problems like I have experienced.

# Information
- Device: Nubia n2 lite
- Android version: 8.1.0
- Application version: 2.0.2

# Recording of the bug
https://youtu.be/2nwfVdCCHis

**Comment by zouroboros** [comment]
24356 is not a valid zip code in Germany. But the error message could be improved.
