### ISSUE TITLE
Setting option doesn't work. 

### ISSUE THREAD

**Issue by PeerzadaZeeshan** [zouroboros/filmchecker#5]
#### Expected behavior
I opened the app and want to open the setting option. 

#### Actual behavior 
I  opened the application and wants to go in setting option and it doesn't works. 

#### How to reproduce
Download the app and open it. Now go to the option shown in image below![IMG_20180313_092625.jpg](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520913885/o94cfahqw92p6lsworrd.jpg). After opening this option then three dots are on the top right corner of the app. Tap on this option then setting option appears press on it to reproduce the bug. 

* Browser: FilmChecker. 
* Version:1.2.2
* Operating system:5.1.1

#### Recording Of The Bug
The recording of the bug is in the GIF. 
![20180313_090111.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520914099/zv6fsqktejced4ilyx36.gif)

    

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@peerzadazeeshan/setting-option-doesn-t-work">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by zouroboros** [comment]
Thanks for taking the time and creating the bugreport. Since the FilmChecker has no settings I will remove the settings option.

**Comment by zouroboros** [comment]
Fixed with 5dc0376c3bf4e4f86d4207dbfe7024847ba55c7f
